class_name MoveData
extends RefCounted

# Généré par kanto-pipeline/build_moves_data.py depuis pokefirered — ne pas
# éditer à la main, relancer le script pour régénérer/étendre MOVE_KEYS.
# Sous-ensemble volontaire (voir docstring du script), pas les 355 capacités
# du jeu — seulement celles utilisées par le combat de Yohan (zone 3).

const MOVES := {
	"SCRATCH": {
		"name": "Griffe",
		"effect": "EFFECT_HIT",
		"power": 40,
		"type": "NORMAL",
		"category": "PHYSICAL",
		"accuracy": 100,
		"pp": 35,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"EMBER": {
		"name": "Flammèche",
		"effect": "EFFECT_BURN_HIT",
		"power": 40,
		"type": "FIRE",
		"category": "SPECIAL",
		"accuracy": 100,
		"pp": 25,
		"secondary_effect_chance": 10,
		"priority": 0,
	},
	"WATER_GUN": {
		"name": "Pistolet à O",
		"effect": "EFFECT_HIT",
		"power": 40,
		"type": "WATER",
		"category": "SPECIAL",
		"accuracy": 100,
		"pp": 25,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"RAIN_DANCE": {
		"name": "Danse Pluie",
		"effect": "EFFECT_RAIN_DANCE",
		"power": 0,
		"type": "WATER",
		"category": "STATUS",
		"accuracy": 0,
		"pp": 5,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"VINE_WHIP": {
		"name": "Fouet Lianes",
		"effect": "EFFECT_HIT",
		"power": 35,
		"type": "GRASS",
		"category": "SPECIAL",
		"accuracy": 100,
		"pp": 10,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"RAZOR_LEAF": {
		"name": "Tranch'Herbe",
		"effect": "EFFECT_HIGH_CRITICAL",
		"power": 55,
		"type": "GRASS",
		"category": "SPECIAL",
		"accuracy": 95,
		"pp": 25,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"RAPID_SPIN": {
		"name": "Vibraqua",
		"effect": "EFFECT_RAPID_SPIN",
		"power": 20,
		"type": "NORMAL",
		"category": "PHYSICAL",
		"accuracy": 100,
		"pp": 40,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"TACKLE": {
		"name": "Charge",
		"effect": "EFFECT_HIT",
		"power": 35,
		"type": "NORMAL",
		"category": "PHYSICAL",
		"accuracy": 95,
		"pp": 35,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
	"KARATE_CHOP": {
		"name": "Tranchage",
		"effect": "EFFECT_HIGH_CRITICAL",
		"power": 50,
		"type": "FIGHTING",
		"category": "PHYSICAL",
		"accuracy": 100,
		"pp": 25,
		"secondary_effect_chance": 0,
		"priority": 0,
	},
}
